2018-02-08 15:54:15,036 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 510, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 572, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 13: 'demographics.population_density.values.this|floatformat:'1''. Did you forget to register or load this tag?
2018-02-08 15:55:07,961 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 510, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 572, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 13: 'ipv4.ipv4_users.values.this|floatformat:'1''. Did you forget to register or load this tag?
2018-02-08 15:55:09,111 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 510, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 572, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 13: 'ipv4.ipv4_users.values.this|floatformat:'1''. Did you forget to register or load this tag?
2018-02-08 15:55:32,129 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 510, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 572, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 13: 'ipv4.ipv4_users.values.this|floatformat:"1"'. Did you forget to register or load this tag?
2018-02-08 15:55:33,192 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 510, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/template/base.py", line 572, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 13: 'ipv4.ipv4_users.values.this|floatformat:"1"'. Did you forget to register or load this tag?
2018-02-08 16:00:50,682 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.user.values.this'])
KeyError: 'users_in_country.user.values.this'
2018-02-08 16:00:58,816 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.user.values.this'])
KeyError: 'users_in_country.user.values.this'
2018-02-08 16:01:48,658 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.user.values.this'])
KeyError: 'users_in_country.user.values.this'
2018-02-08 16:01:49,651 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.user.values.this'])
KeyError: 'users_in_country.user.values.this'
2018-02-08 16:01:50,292 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.user.values.this'])
KeyError: 'users_in_country.user.values.this'
2018-02-08 16:02:02,508 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.User.values.this'])
KeyError: 'users_in_country.user.values.this'
2018-02-08 16:02:04,239 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.User.values.this'])
KeyError: 'users_in_country.User.values.this'
2018-02-08 16:02:05,015 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.User.values.this'])
KeyError: 'users_in_country.User.values.this'
2018-02-08 16:02:22,473 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.User'])
KeyError: 'users_in_country.User'
2018-02-08 16:02:23,236 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 39, in get_profile
    logger.debug(data['ipv4']['users_in_country.User'])
KeyError: 'users_in_country.User'
2018-02-08 16:55:02,334 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('users_in_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 276, in get_objects_by_geo
    fields = [getattr(db_model, f) for f in fields]
AttributeError: type object 'Model' has no attribute 'users_in_world'
2018-02-08 16:55:04,538 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('users_in_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 276, in get_objects_by_geo
    fields = [getattr(db_model, f) for f in fields]
AttributeError: type object 'Model' has no attribute 'users_in_world'
2018-02-08 16:57:18,807 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('users_in_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 276, in get_objects_by_geo
    fields = [getattr(db_model, f) for f in fields]
AttributeError: type object 'Model' has no attribute 'users_in_world'
2018-02-08 16:57:19,667 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('users_in_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 276, in get_objects_by_geo
    fields = [getattr(db_model, f) for f in fields]
AttributeError: type object 'Model' has no attribute 'users_in_world'
2018-02-08 16:57:40,799 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('users_in_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 276, in get_objects_by_geo
    fields = [getattr(db_model, f) for f in fields]
AttributeError: type object 'Model' has no attribute 'users_in_world'
2018-02-08 16:57:56,542 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('users_in_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 276, in get_objects_by_geo
    fields = [getattr(db_model, f) for f in fields]
AttributeError: type object 'Model' has no attribute 'users_in_world'
2018-02-08 16:57:57,120 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('users_in_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 276, in get_objects_by_geo
    fields = [getattr(db_model, f) for f in fields]
AttributeError: type object 'Model' has no attribute 'users_in_world'
2018-02-08 16:58:44,333 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 16:58:45,268 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 16:59:44,525 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 16:59:45,271 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:00:17,164 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:00:19,055 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:00:19,712 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:01:08,664 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:01:09,420 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:01:10,016 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:02:07,103 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:03:49,021 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:16:40,559 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:16:41,144 [WARNING] django.request: Not Found: /favicon.ico
2018-02-08 17:18:12,102 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:18:12,865 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:18:13,857 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-08 17:18:14,165 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-09 09:08:09,733 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 313, in get_objects_by_geo
    % (db_model.__table__.name, geo.geoid, geo.version))
LocationNotFound: users_in_world for geography country-ZA version '' not found
2018-02-09 09:08:14,125 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 313, in get_objects_by_geo
    % (db_model.__table__.name, geo.geoid, geo.version))
LocationNotFound: users_in_world for geography country-ZA version '' not found
2018-02-09 09:22:35,527 [WARNING] django.request: Not Found: /configuration.xml
2018-02-09 09:24:21,558 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
2018-02-09 09:24:22,733 [ERROR] django.request: Internal Server Error: /profiles/country-ZA-south-africa/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 47, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 16, in get_ipv4_profile
    worldUsers, total = get_stat_data('country_or_world', geo, session,table_fields=['country_or_world'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 510, in get_stat_data
    data['numerators']['this'] += obj.total
TypeError: unsupported operand type(s) for +=: 'float' and 'Decimal'
