2018-02-06 15:17:29,678 [ERROR] django.request: Internal Server Error: /profiles/world-WW-earth/
Traceback (most recent call last):
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 62, in dispatch
    return TemplateView.dispatch(self, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/django/views/generic/base.py", line 157, in get
    context = self.get_context_data(**kwargs)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/views.py", line 74, in get_context_data
    profile_data = profile_method(self.geo, self.profile_name, self.request)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 34, in get_profile
    data[section] = func(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/profiles.py", line 56, in get_ipv4_profile
    return ipv4.get_ipv4_profile(geo, session)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/wazimap_ww/wazimap_ww/ipv4.py", line 15, in get_ipv4_profile
    countrieUsers, total = get_stat_data('users_or_not', geo, session,table_fields=['users_or_not'])
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 421, in get_stat_data
    only=only, exclude=exclude, data_table=data_table)
  File "/etc/apache2/louw/projects/afrinic/firstdjango/ENV/local/lib/python2.7/site-packages/wazimap/data/utils.py", line 313, in get_objects_by_geo
    % (db_model.__table__.name, geo.geoid, geo.version))
LocationNotFound: users_in_country for geography world-WW version '' not found
